### ISSUE TITLE
Implement snapshot scheduling and garbage collection

### ISSUE THREAD

**Issue by bmr-cymru** [snapshotmanager/snapm#53]
# Summary
Add the ability to configure automatic, recurring creation of snapshot sets according to a given schedule and retention policy. Scheduled snapshot sets should be automatically deleted when the retention policy expires.

## Design
Snapshot manager will implement this using an extension to the snapshot set naming scheme to allow iterations of a snapshot set with a common base name. The [systemd timer](https://www.freedesktop.org/software/systemd/man/latest/systemd.timer.html#) subsystem and template units will be used to trigger creation and garbage collection at the scheduled time and a configuration file placed in `/etc/snapm/schedule.d/$name.conf` at schedule creation time will provide the parameters for the creation and retention of the named schedule.

The template units will execute `snapm create` with the corresponding configuration file according to the unit instance:

### snapm-create@.timer
```
[Unit]
Description=Scheduled %I snapshot set creation timer
Documentation=man:snapm(8) man:snapm-conf(5)

[Timer]
Unit=snapm-create@%i.service

[Install]
WantedBy=timers.target
```

### snapm-create@.service
```
[Unit]
Description=Create snapshot sets for schedule %I
Documentation=man:snapm(8) man:snapm-conf(5)
After=local-fs.target

[Service]
Type=oneshot
ExecStart=snapm snapset create -c %i
```

A similar pair of timer/service units will execute `snapm schedule gc -c %i.conf` on a regular schedule to run garbage collection with the configured policies.

Users can schedule snapshot set creation on arbitrary calendar events using the systemd [calendarspec notation](https://www.freedesktop.org/software/systemd/man/latest/systemd.time.html). 
Cleanup should offer flexibility and a range of policies to govern snapshot retention:

* **Keep all**
  * Never automatically delete snapshot sets (discouraged, requires manual monitoring and intervention or additional automation)
* **Keep number (N)**
  * Delete all but the N most recent snapshot sets
* **Keep by age (TIMESPAN)**
  * Delete all snapshot sets older than TIMESPAN
* **Keep by timeline (KEEP_HOURLY, KEEP_DAILY, KEEP_WEEKLY, KEEP_MONTHLY, KEEP_QUARTERLY, KEEP_YEARLY)**
  * Similar to existing tools
    * Retains the N most recent snapshot sets for each time interval
    * Snapper timeline policies: http://snapper.io/manpages/snapper-configs.html
    * timeshift [schedules](https://github.com/teejee2008/timeshift/blob/master/images/settings_schedule.png):
    * Apple Time Machine default policy: https://support.apple.com/en-gb/104984
      * Create defaults to backups on a dedicated device rather than snapshots
      * By default cleanup is only triggered when running low on space
      * Snapshots and custom schedules can be configured with a 3rd party tool: https://tclementdev.com/timemachineeditor/

## UI

The proposed UI adds a new `schedule` command type to `snapm`:

```
# snapm schedule --help
usage: snapm schedule [-h] {create,delete,enable,disable,list,show,gc} ...

positional arguments:
  {create,delete,enable,disable,list,show}
    create              Create a new snapshot set schedule
    delete              Delete an existing snapshot set schedule
    enable              Enable the named snapshot set schedule
    disable             Disable the named snapshot set schedule
    list                List configured snapshot set schedules
    list-schedule       List occurrences of schedules
    show                Display snapshot set schedules
    gc                  Run garbage collection for snapshot set schedule

options:
  -h, --help            show this help message and exit
```

N.b.: looking for a better name for `list-schedule`. It's a list command, but it displays the *occurrences* of schedules.

Creating a schedule:

```
# snapm schedule create hourly --oncalendar hourly --size-policy 25%SIZE / /srv /var
ScheduleName:    hourly
OnCalendar: hourly
Normalised: *-*-* *:00:00
NextElapse: Thu 2025-03-20 16:00:00 GMT
Sources: / /srv /var
NrSnapshots: 3
Enabled: yes
```

Listing schedules
```
# snapm schedule list
ScheduleName    OnCalendar  Normalized    NextElapse                  Sources       NrSnapshots  Enabled
hourly          hourly      *-*-* *:00:00 Thu 2025-03-20 16:00:00 GMT / /srv /var   3            yes
```

The UI is subject to change as the underlying components are completed.

## Sub-tasks

* [x] Extend naming scheme to allow iterations of a snapshot set with a common base name
* [x] Implement `CalendarSpec` abstraction for systemd timer unit configuration
* [x] `CalendarSpec` unit tests
* [x] Add config file support to Manager and implement directory structure in `/etc/snapm/`
* [x] Add config file support to `snapm create` for scheduled snapset creation
* [x] Implement template systemd timer and service units for creation and garbage collection
* [x] Implement abstraction for schedule instances (`Schedule`)
  * Tracks timer configuration, name, sources, size policy, enabled/disabled, nr snapshots, next elapse
* [x] `Schedule` unit tests
* [x] Implement interface to create, delete, enumerate and modify schedules (`Scheduler`)
  * Tracks and manages configuration files in `/etc/snapm/schedule.d`. interfaces with systemd
* [x] `Scheduler` unit tests (possibly via systemd-nspawn?)
* [x] Interface with systemd to enable/disable schedule timers on request
* [x] Expose `Scheduler` via `Manager` and allow users of `Manager` to access `Scheduler` interface
* [x] Integration tests for `Manager`/`Scheduler` interfaces
* [x] Implement `snapm.command` procedural wrappers for schedule operations
* [x] Implement `snapm.command` `_*_cmd()` handlers for schedule subcommands
* [x] Integration tests for new subcommands
* [x] Add subparser definitions for schedule commands
* [x] Document new commands in README.md and snapm(8)
* [x] Document configuration format in snapm-conf(5)
* [x] Update RPM spec file to add `snapm-conf` subpackage with skeleton `/etc/snapm` content

**Comment by bmr-cymru** [comment]
> N.b.: looking for a better name for `list-schedule`. It's a list command, but it displays the _occurrences_ of schedules.

One option would be to make this a variation of `snapm schedule list`, e.g. `snapm schedule list --occurrences` (or something less annoying to type...).
